#!/bin/bash
BREWHOME=~/.brew-file
BREWFILE=./Brewfile

if [ -d $BREWHOME ]
then
  cd $BREWHOME
  if [ -f $BREWFILE ]
  then
    echo "[brew]:"
    echo "-- update"
    brew update
    echo "-- check"
    brew bundle check
    echo "-- install"
    brew bundle install
    echo "-- cleanup"
    brew bundle cleanup --force
    echo "-- outdated"
    UPGRADE=`brew outdated`
    [ ! -z "$UPGRADE" ] && brew upgrade
    echo "-- doctor"
    brew doctor
    echo "-- bun"
    which bun
    bun upgrade
    echo "-- nit"
    which nit
    echo "-- yarn"
    which yarn
    yarn --version
    echo "-- npm"
    which npm
    npm --version
    echo "-- node"
    which node
    node --version
    echo "-- ssc"
    which ssc
    ssc --version
    echo "-- verify"
    LOG=`nit`
    case $LOG in
      *"git push"*)
        git push;;
      *"nothing to commit"*)
        printf "";;
      *)
        git commit -a -m ">> updating brew"
        git push;;
    esac
    printf "\a"
    echo "-- done"
  else
    echo "ERROR -- missing ${BREWFILE}"
  fi
else
  echo "ERROR -- missing ${BREWHOME}"
fi
